### ISSUE TITLE
A bit of confusion 2/3rd of the way down

### ISSUE THREAD

**Issue by dabanhfreak** [mike11207/single-gpu-passthrough-amd-gpu#4]
EDIT figured the first part, the second query is as follows:

> Now go into virt-manager once more and add the parts of the GPU to the virtual machine
> 
> Go into your GPU in virt-manager and add this line:
> 
> <----THIS ONE
> 
> Remove spice / qxl stuff in VM`
 
A bit confused by what THIS ONE is referring to, and where to remove 'spice/qxl

**Comment by Stay1444** [comment]
A bit late, but it seems that they pasted the XML line into the markdown without wrapping it in a codeblock, and since HTML/Markdown is basically XML github got confused and just removed that line all together.

If you open the README.md file raw, you can see that the readme is actually like this
```
  Now go into virt-manager once more and add the parts of the GPU to the virtual machine
  
  Go into your GPU in virt-manager and add this line:
  <source>
  
  <rom file="/var/lib/libvirt/vbios/GPU.rom"/>    <----THIS ONE
  
  <address type="pci" domain="0x0000" bus="0x06" slot="0x00" function="0x0"/>
  
  Remove spice / qxl stuff in VM

enter these commands to make the hooks for our VM
```

You can see what line they are referencing there
